openapi: 3.0.0
info:
  title: Swagger Server API
  version: "1.0"
paths:
  /validations:
    post:
      summary: Create new validations
      operationId: swagger_server.controllers.validation_controller.create_validations
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BundleList'
      responses:
        201:
          description: Validations created
  /list:
    get:
      summary: Get all Resource validations from MongoDB
      operationId: swagger_server.controllers.validation_controller.get_all_entries
      responses:
        200:
          description: A list of all entries from MongoDB
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Bundle'
components:
  schemas:
    Bundle:
      type: object
      properties:
        bundle:
          type: object
          additionalProperties: true
          description: Any valid JSON object
    BundleList:
      type: object
      properties:
        bundles:
          type: array
          items:
            $ref: '#/components/schemas/Bundle'